import React from "react";
import { Typography, Paper } from "@material-ui/core";

const PrivacyDetailsText = () => (
  <Paper style={{ maxHeight: "50vh", overflow: "scroll", padding: "1rem" }}>
    <Typography gutterBottom>
      Your data is encrypted locally on your computer using a secure encryption
      method known as a sealed box. This process uses an encryption key
      generated by the application. The encrypted data is saved to a file on
      your computer at a location you choose.
    </Typography>

    <Typography gutterBottom>
      You maintain complete control over the encrypted file. You decide when and
      how to share it with the research team. The file remains on your computer
      until you choose to share it through your preferred method (email, file
      transfer, etc.).
    </Typography>

    <Typography gutterBottom>
      For each sentence you export, our application stores a unique random ID on
      your computer. This allows you to review your exported phrases and make
      changes if needed. You can re-export at any time with different
      selections.
    </Typography>
  </Paper>
);

export default PrivacyDetailsText;
